### ISSUE TITLE
GWE starts with empty window

### ISSUE THREAD

**Issue by develop7** [flathub/com.leinardi.gwe#12]
Repro: start GWE

Expected: GWE functions normally

Instead: a window with no data in it is shown, as per the screenshot below

![image](https://user-images.githubusercontent.com/89889/56313065-55720f00-615a-11e9-9fe1-88121731f244.png)

`flatpak run -v`  output — <details>
```
~>  flatpak run -v com.leinardi.gwe
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/develop7/.local/share/flatpak
F: Opening user flatpak installation at path /home/develop7/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/develop7/.local/share/flatpak
F: Cleaning up unused container id 1283391036
F: Allocated instance id 2245169767
F: Add defaults in dir /com/leinardi/gwe/
F: Add locks in dir /com/leinardi/gwe/
F: Allowing dri access
F: Allowing x11 access
F: Running 'bwrap --args 33 /usr/lib/flatpak-dbus-proxy --args=35'
F: Running 'bwrap --args 33 gwe'

(gwe:2): Gtk-WARNING **: 21:46:47.075: Locale not supported by C library.
	Using the fallback 'C' locale.

(gwe:2): Gtk-WARNING **: 21:46:47.907: gtk_window_present_with_time() should not be called with 0, or GDK_CURRENT_TIME as a timestamp, the timestamp should instead be gathered at the time the user initiated the request for the window to be shown
ERROR: Error while getting status
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gwe/repository.py", line 84, in get_status
    xlib_display = display.Display(self._ctrl_display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
gwe.Xlib.error.DisplayConnectionError: Can't connect to display ":99.0": b'No protocol specified\n'
ERROR: Set cooling error: Can't connect to display ":99.0": b'No protocol specified\n'
NoneType: None
ERROR: Error while getting status
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gwe/repository.py", line 84, in get_status
    xlib_display = display.Display(self._ctrl_display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
gwe.Xlib.error.DisplayConnectionError: Can't connect to display ":99.0": b'No protocol specified\n'
ERROR: Set cooling error: Can't connect to display ":99.0": b'No protocol specified\n'
NoneType: None
ERROR: Error while getting status
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gwe/repository.py", line 84, in get_status
    xlib_display = display.Display(self._ctrl_display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
gwe.Xlib.error.DisplayConnectionError: Can't connect to display ":99.0": b'No protocol specified\n'
ERROR: Set cooling error: Can't connect to display ":99.0": b'No protocol specified\n'
NoneType: None
ERROR: Error while getting status
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gwe/repository.py", line 84, in get_status
    xlib_display = display.Display(self._ctrl_display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
gwe.Xlib.error.DisplayConnectionError: Can't connect to display ":99.0": b'No protocol specified\n'
ERROR: Set cooling error: Can't connect to display ":99.0": b'No protocol specified\n'
NoneType: None
ERROR: Error while getting status
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gwe/repository.py", line 84, in get_status
    xlib_display = display.Display(self._ctrl_display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
gwe.Xlib.error.DisplayConnectionError: Can't connect to display ":99.0": b'No protocol specified\n'
ERROR: Set cooling error: Can't connect to display ":99.0": b'No protocol specified\n'
NoneType: None
ERROR: Error while getting status
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gwe/repository.py", line 84, in get_status
    xlib_display = display.Display(self._ctrl_display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
gwe.Xlib.error.DisplayConnectionError: Can't connect to display ":99.0": b'No protocol specified\n'
ERROR: Set cooling error: Can't connect to display ":99.0": b'No protocol specified\n'
NoneType: None
ERROR: Error while getting status
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gwe/repository.py", line 84, in get_status
    xlib_display = display.Display(self._ctrl_display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.7/site-packages/gwe/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
gwe.Xlib.error.DisplayConnectionError: Can't connect to display ":99.0": b'No protocol specified\n'
ERROR: Set cooling error: Can't connect to display ":99.0": b'No protocol specified\n'
NoneType: None
```
</details>

**Comment by leinardi** [comment]
Please open an issue on the official project issue tracker filling all the requested info: https://gitlab.com/leinardi/gwe/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=
